#server:
# port: 9000
   
management:
  endpoints:
    web:
      base-path: /stockapp
      exposure:
        include:
        - "*" 
        exclude:
        - "beans"
  endpoint:
    health:
      enabled: true
    shutdown:
      enabled: true 
spring:
  application:
    name: StockApp 
  profiles:
    active: "dev" 
#  config:
#      import:
#      - configserver:http://localhost:8888  
       

  datasource:
    url: jdbc:mysql://localhost:3306/stockdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 786786786
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  
  data:
    mongodb:
      host: localhost
      port: 27017
      database: stockdb  



  
  
            
 